# Generated by Django 3.2.6 on 2021-08-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year',
            new_name='publish_year',
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.IntegerField(default=1),
        ),
    ]
